<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Database\Seeder;

class SiswaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nama_siswa' => 'Ahmad Fauzi',
                'nik' => '3578012305000001',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2000-05-23',
                'agama' => 'islam',
                'email' => 'ahmad.fauzi@email.com',
                'no_telepon' => '081234567001',
                'alamat' => 'Jl. Raya Darmo No. 10, Surabaya',
                'jenis_tinggal' => 'rumah_orang_tua',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'sma_smk',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'pelajar',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Siti Nurhaliza',
                'nik' => '3578014506990002',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1999-06-05',
                'agama' => 'islam',
                'email' => 'siti.nurhaliza@email.com',
                'no_telepon' => '081234567002',
                'alamat' => 'Jl. Ijen No. 25, Malang',
                'jenis_tinggal' => 'kos',
                'kota' => 'Malang',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'sma_smk',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'pelajar',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Budi Santoso',
                'nik' => '3578011201010003',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Sidoarjo',
                'tanggal_lahir' => '2001-01-12',
                'agama' => 'kristen',
                'email' => 'budi.santoso@email.com',
                'no_telepon' => '081234567003',
                'alamat' => 'Jl. Ahmad Yani No. 100, Sidoarjo',
                'jenis_tinggal' => 'rumah_sendiri',
                'kota' => 'Sidoarjo',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'd3',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'karyawan_swasta',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Dewi Kartika',
                'nik' => '3578015607980004',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Gresik',
                'tanggal_lahir' => '1998-07-16',
                'agama' => 'islam',
                'email' => 'dewi.kartika@email.com',
                'no_telepon' => '081234567004',
                'alamat' => 'Jl. Veteran No. 45, Gresik',
                'jenis_tinggal' => 'rumah_orang_tua',
                'kota' => 'Gresik',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'sma_smk',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'tidak_bekerja',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Rizky Pratama',
                'nik' => '3578010903020005',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2002-03-09',
                'agama' => 'katolik',
                'email' => 'rizky.pratama@email.com',
                'no_telepon' => '081234567005',
                'alamat' => 'Jl. Basuki Rahmat No. 77, Surabaya',
                'jenis_tinggal' => 'rumah_saudara',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'smp',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'pelajar',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Anisa Rahmawati',
                'nik' => '3578012811970006',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Mojokerto',
                'tanggal_lahir' => '1997-11-28',
                'agama' => 'islam',
                'email' => 'anisa.rahma@email.com',
                'no_telepon' => '081234567006',
                'alamat' => 'Jl. Majapahit No. 33, Mojokerto',
                'jenis_tinggal' => 'kos',
                'kota' => 'Mojokerto',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'd4/s1',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'freelancer',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Eko Prasetyo',
                'nik' => '3578011507000007',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Lamongan',
                'tanggal_lahir' => '2000-07-15',
                'agama' => 'islam',
                'email' => 'eko.prasetyo@email.com',
                'no_telepon' => '081234567007',
                'alamat' => 'Jl. Pahlawan No. 8, Lamongan',
                'jenis_tinggal' => 'asrama',
                'kota' => 'Lamongan',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'sma_smk',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'pelajar',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Maya Indah Sari',
                'nik' => '3578013003010008',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2001-03-30',
                'agama' => 'hindu',
                'email' => 'maya.indah@email.com',
                'no_telepon' => '081234567008',
                'alamat' => 'Jl. Diponegoro No. 55, Surabaya',
                'jenis_tinggal' => 'rumah_orang_tua',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'sma_smk',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'wiraswasta',
                'status_siswa' => 0,
            ],
            [
                'nama_siswa' => 'Fajar Nugroho',
                'nik' => '3578010204990009',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Jombang',
                'tanggal_lahir' => '1999-04-02',
                'agama' => 'islam',
                'email' => 'fajar.nugroho@email.com',
                'no_telepon' => '081234567009',
                'alamat' => 'Jl. KH Wahid Hasyim No. 12, Jombang',
                'jenis_tinggal' => 'rumah_sendiri',
                'kota' => 'Jombang',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'd3',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'karyawan_swasta',
                'status_siswa' => 1,
            ],
            [
                'nama_siswa' => 'Putri Ayu Lestari',
                'nik' => '3578011708020010',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Tuban',
                'tanggal_lahir' => '2002-08-17',
                'agama' => 'buddha',
                'email' => 'putri.ayu@email.com',
                'no_telepon' => '081234567010',
                'alamat' => 'Jl. Panglima Sudirman No. 20, Tuban',
                'jenis_tinggal' => 'kos',
                'kota' => 'Tuban',
                'provinsi' => 'Jawa Timur',
                'pendidikan_terakhir' => 'sma_smk',
                'abk' => 'tidak_ada',
                'pekerjaan' => 'pelajar',
                'status_siswa' => 0,
            ],
        ];

        foreach ($data as $item) {
            Siswa::updateOrCreate(
                ['nik' => $item['nik']],
                $item
            );
        }
    }
}
